export type ArticleLocale = "en" | "fa";

export type LocalizedText = {
  en: string;
  fa: string;
};

export type ArticleContent = {
  slug: string;
  author: string;
  startPage: number;
  category: LocalizedText;
  title: LocalizedText;
  description: LocalizedText;
  body: {
    en: string[];
    fa: string[];
  };
};

export const articles: ArticleContent[] = [
  {
    slug: "activism-and-social-movements",
    author: "Hamish Jenkins and Yvon Poirier",
    startPage: 2,
    category: {
      en: "Histories, concepts and theories",
      fa: "تاریخ‌ها، مفاهیم و نظریه‌ها",
    },
    title: {
      en: "Activism and social movements",
      fa: "کنشگری و جنبش‌های اجتماعی",
    },
    description: {
      en: "A concise overview of the role of activism and social movements in the development of the social and solidarity economy.",
      fa: "مروری کوتاه بر نقش کنشگری و جنبش‌های اجتماعی در شکل‌گیری اقتصاد اجتماعی و همبستگی.",
    },
    body: {
      en: [
  "Activism and social movements",
  "INTRODUCTION",
  "Given the diversity of social and solidarity economy (SSE) experiences within and between countries and continents, it is not surprising that scholarly studies on the SSE and social movements are fraught with divergent views and understandings, especially since they tend to be associated with distinct fields of academic research that so far rarely intersect. Should we think in terms of a relationship, or lack thereof, between the SSE and social movements, or is the SSE in itself a social movement that is part of broader movements (from local to global levels) aiming to challenge the dominant neoliberal economic model (Laville et al. 2017)? This entry proposes that it is both: SSE entities and ecosystems are often the result of various forms of social movements’ activism in different parts of the world, whether or not they stay connected to social movements thereafter. And significant parts of the overall SSE constellation can be described as a converging social movement (or ‘movement of movements’) with a plurality of views that are in articulation with other social movements; not only to resist the harmful socio-environmental effects of the current economic model but also to demonstrate, through practice, concrete alternatives. These experiments, at the level of the organization/ enterprise and the local territory, given the right political conditions and motivation of the actors concerned, can be scaled up or ‘mainstreamed’ through enabling public policy changes. Advocacy, contestation, policy influence, and the co-construction of policy via SSE intermediary organizations and their allies play an important role in this process (see also entry 55, ‘Supporting Organizations and Intermediaries’ and entry 47, ‘Local and Territorial Development Plans’).",
  "At this juncture, the question is whether the end result of such developments is the incre mental growth of economic activity undertaken through SSE principles at the micro and meso levels, in a context where unsustainable production and consumption patterns remain relatively unchanged. Alternatively, these advances can be seen as stepping-stones to consolidate social movements aiming at more fundamental macro-changes to democratize the overall economy and politics itself (Laville et al. 2017).",
  "DEFINING SOCIAL MOVEMENTS IN THE CONTEXT OF THE SSE",
  "Since the 1970s, social movements have become a subject of multidisciplinary academic studies, presenting slightly varying elements to define what constitutes a social movement. For the purposes of this entry, we will use the definition provided by James and van Seters (2014) in the context of their study of social movements’ mobilization against neoliberal globalization, or the ‘alter-globalization‘ movement:",
  "Defining a social movement entails a few minimal conditions of ‘coming together’: (1.) the formation of some kind of collective identity; (2.) the development of a shared normative orientation; (3.) the sharing of concern for change of the status quo and (4.) the occurrence of moments of practical action that are at least subjectively connected together across time addressing this concern for change. Thus, we define a social movement as a form of political association between persons who have at least a minimal sense of themselves as connected to others in common purpose and who come together across an extended period of time to effect social change in the name of that purpose. (James and van Seters 2014, xi)",
  "In addition to these generic elements, a distinctive feature of social movements related to the SSE (especially compared to primarily protest-based movements) is the combination of political activism with solidarity-based forms of economic activities that can change material conditions in people’s daily lives and demonstrate in concrete terms that alternative economic models (especially at local and territorial levels) are possible (Laville et al. 2017; Zimmer and Eum 2017). In section 1.4, we suggest that large parts of the myriad entities throughout the world that recognize themselves as part of the SSE are converging, from local to global levels, into a de facto social movement (or ‘movement of movements’) that meets these minimal conditions; albeit with their own tensions and contradictions, as well as their own strengths and weaknesses vis-à-vis other social movements with which they seek to cooperate. First, however, this entry examines social movements as catalysts of SSE.",
  "1.2 SOCIAL MOVEMENTS AS CATALYSTS OF THE SSE",
  "SSE initiatives are typically the result of the activism of social movements and alliances that have common affinities, whether thematic (for example, environmental protection, agroecology, food sovereignty, health, social and economic justice, anti-extractivism, the commons) or identity based (for example, small and landless farmers, consumers, workers unions, informal workers’ associations, feminist movements, indigenous peoples, religious groups). The forms of action are in part determined by the political context in which they operate. They may include relatively soft forms of mobilization, such as bypassing agro-industrial production and distribution through short local organic food supply networks, or the creation of SSE initiatives to combat unemployment and (re)generate sources of livelihoods. Another option may involve more radical operations such as the illegal or semi-legal occupation of land/ territories, wherein SSE ‘microcosms’ can develop with some degree of autonomy vis-à-vis capitalistic relations, such as the Zapatista movement in Chiapas, Mexico, the Landless Rural Workers’ Movement (Movimento dos Trabalhadores Sem Terra, MST) in Brazil, or the more recent Zones à Défendre (zadiste) movements in France (Laville et al. 2017). SSE social movements, like other social movements, are best understood through a ‘multi-organizational field’ approach: namely, the need to understand them in relation to the confluence of different currents of thought and pre-existing movements (Curtis and Zurcher 1973; Laville et al. 2017). Using this approach, this entry illustrates the role of social movements in catalyzing and accompanying SSE agroecological consumer‒producer networks in South Korea and France (Box 1.1), and in generating jobs and livelihoods in Colombia and Brazil (Box 1.2).",
  "BOX 1.1 SSE AGROECOLOGICAL CONSUMER‒PRODUCER MOVEMENTS",
  "The Republic of Korea",
  "The Republic of Korea (or South Korea) today is one of the countries with the most vibrant SSE ecosystem in the world, backed by many local authorities, as described in entry 47, ‘Local and Territorial Development Plans’. The beginnings of the SSE can be traced to the creation of credit unions by the ecclesiastical movement in the 1970s, inspired by the Antigonish movement in Canada (blending adult education, cooperatives, microfinance and rural community development). From the mid-1980s onward, building on earlier rural agricultural cooperative experiments, a new form of consumer cooperatives called Hansalim brought together consumers and producers with the aim of developing solidarity-based relations between urban consumers and rural organic food producers. A coalition of environmental, feminist and neighbourhood movements and citizen mobilization helped to organize the daily provisioning of healthy organic products. It has been observed that these movements are a continuum of earlier pro-democracy movements from the 1970s against military dictatorship (notably students, intellectuals, church groups) that are still active to day, notably through the mass demonstrations in 2016‒17 calling for the impeachment of President Park Geun-hye over a corruption scandal. The ‘social movement’ dimension of consumer cooperatives also remains alive through their participation in the organization of public demonstrations in favour of environmental protection and food sovereignty (Zimmer and Eum 2017).",
  "France",
  "Similarly in France, the Associations pour le Maintiend’une Agriculture Paysanne, AMAP (Associations for the Preservation of Small-Scale Farming), which also promotes solidarity partnerships between smallholder farmers and consumers, began operation in 2001 through the combined efforts of an alliance of small farmer, environmental and consumer movements, Alliance Paysans‒Écologistes‒Consommateurs (Alliance PEC) created in 1991. Among them is the Confédération Paysanne, the national union of smallholder farmers and agricultural workers which defends a ‘realistic alternative’ to industrial agriculture, based on social, solidarity and ecological principles, and is one of the founders of the global small farmers movement, Via Campesina, campaigning for the principles of food sovereignty and solidarity worldwide (http:// c onfederati onpaysanne .fr). According to the latest surveys in France, there are well over 2000 AMAP and over 250 000 people involved in the movement, in both producer‒consumer networks and awareness-raising campaigns (Zimmer and Eum 2017; http:// miramap .org). The national network (Mouvement inter-régional des Amap) is part of URGENCI, which is an international network of grassroots organizations that is present in 32 countries. It follows similar principles and types of action through different names, such as community supported agriculture (CSA), and is generally referred to as local solidarity-based partnerships for agroecology (LSPAs). The AMAP are part of the wider ecologist movement in France, which formed a political party (Les Verts, now called Les Écologistes) that played an important role in supporting the elaboration and adoption of the 2014 framework law on SSE proposed by the Socialist Party then in power (Laville et al. 2017; Zimmer and Eum 2017).",
  "BOX 1.2 MOVEMENTS FOR EMPLOYMENT AND LIVELIHOODS",
  "Colombia",
  "In Colombia, SSE initiatives emerged in the 1960s, although solidarity-based economic principles date back to pre-Hispanic times through indigenous practices of mutual help and reciprocity (named minga, manos vueltas, convite). Since the 1960s, the movements developing concrete SSE projects in the field had already been promoting the idea of incorpo rating solidarity economy principles into law. These movements were significantly driven by Catholic activists adhering to the Theology of Liberation through the diocesan social pastoral secretariat (Sepas). They also drew on the experiences of cooperativism in Europe and Canada. Caught between a repressive oligarchic regime and armed rebel guerrillas, activists found in SSE a non-threatening manner to implicitly express their ideological position against capitalistic development, while providing alternative livelihood opportunities to those proposed by the armed revolutionaries. In the southern region of the Department of Santander, activities included support for the creation and development of cooperatives principally in rural development, but also finance, transport, education and health. A third of the population (450 000 persons) work in 200 created cooperatives. In addition, an in termediary organization, El Commun, was established to enable dialogue with the state and to promote SSE territorial development, as well as networks bringing together academics, non-governmental organizations (NGOs) and community organizations to plan and implement local SSE development initiatives.",
  "Elements of the concept of the solidarity economy were first introduced in the Constitution of 1991. The legal framework for SSE entities, regrouped in two categories (solidarity enterprises and economic organizations for solidarity-based development), was later spelt out in law 545 of 1998 on ‘the solidarity economy and entities of a cooperative nature’. It is noteworthy that solidarity economy was also recognized in the peace agreement between the Colombian Government and Revolutionary Armed Forces – Peoples’ Army (FARC EP) in 2016 (Hataya 2017).",
  "Brazil",
  "In neighbouring Brazil, the ecclesiastical movement also played a leading role in generating SSE initiatives throughout the country together with other social movements, especially the workers’ movement and its extension into a major political party. The draconian neoliberal policies of austerity, privatization and trade liberalization undertaken in the 1980s and 1990s generated mass long-term unemployment, poverty and social exclusion throughout the country. From the 1990s onward, SSE initiatives developed initially as a survival strategy for a growing number of unemployed workers through Alternative Community Projects (PACs). These were established by the Catholic NGO Caritas and SSE incubators called Incubadora Tecnológica de Cooperativas Populares (ITCP) and hosted by public universities and NGOs, and resulted from the mobilization of university professors, students, workers and grassroots activists. SSE initiatives began spreading with the involvement of a wider number of movements and groups, including landless rural workers, waste collectors, artisans, indigenous peoples and Afro Brazilian groups, women’s movements, and neighbourhood assemblies.",
  "One of the two major national trade union confederations, the Central Única dos Trabalhadores (CUT) embraced the solidarity economy as a creative response to severe economic crises and the devastating impact on the labour market. In 1999, it set up an Agency for Solidarity Development with other NGOs and SSE organizations, in order to support the creation and consolidation of solidarity cooperatives and enterprises as means to generate employment and income. In parallel, solidarity economy was increasingly being supported at municipal and state levels by elected officials from the political party emanating from the workers’ movement, the Partido dos Trabalhadores (PT). After it gained power at the federal level in 2002, between 2003 and 2016 the PT government developed a wide range of public policies and programmes to support the SSE through the newly created National Secretariat for Solidarity Economy (SENAES), as described in entry 47, ‘Local and Territorial Development Plans’. Upon creation of the Secretariat, a plenary meeting with representatives of the entire SSE movement in the country was held to create two major national entities: the Fórum Brasileiro de Economia Solidária (FBES) regrouping all solidarity economy-based initiatives and civil society organizations supporting the SSE; and a network of officials from municipal and state governments promoting the SSE in their territories. According to some estimates, over 30 000 organizations and enterprises (SSEOEs) and supporting organizations were created nationwide, involving around 3 million individuals. (Singer and Schiochet 2017; Addor and Rolim Laricchia 2018; CUT 1999)",
  "Some of the main actors propelling the SSE movement in Brazil were also instrumental in the process leading to the World Social Forum discussed in section 1.3.",
  "Many initiatives are the result of a cross-fertilization of ideas and practices from across countries and continents. The success of initiatives has in many cases brought political momentum toward the adoption of public policies in favour of the SSE, notably through political parties with affinities to the leading social movements. In some cases, the actors of SSE initiatives, once well established, distance themselves from activism, prioritizing the daily economic operations of their enterprise or organization (‘routinization’), marking a partial or complete break from the social movement that created them. In other cases, the ties with the social movement remain active or evolve into new movements (Zimmer and Eum 2017).",
  "1.3 THE SSE: AN EMERGING GLOBAL MOVEMENT WITHIN THE ALTER-GLOBALIZATION MOVEMENT",
  "The spread of the SSE through social movements is not the fruit of a fully fledged theory or blueprint imposed through a top-down approach. Rather, it reflects a bottom-up process representing very diverse experiences, where actors respond to challenges within their own context; some de facto, undertaking activities involving SSE principles without recognizing themselves as part of a collective identity called ‘social and solidarity economy‘. As noted in Boxes 1.1 and 1.2, some movements have studied the experience of cooperativism from other countries and applied its principles to their own realities. However, cooperatives are only a part of the broader set of SSEOEs described in other entries of this Encyclopedia. This section examines: (1) the conditions of coming together of significant parts of the overall SSE community as a global social movement as defined by James and van Seters (2014) cited above; and (2) the relationship and articulation between the SSE movement and other social movements mobiliz ing against the neoliberal agenda, increasingly referred to as the alter-globalization movement.",
  "The SSE: An Emerging Global Social Movement",
  "The gradual construction of collective identity and shared normative orientation among SSE actors around the world has been a slow process of dialogue and mutual learning. To simplify what is in fact a much larger nomenclature, it has been the convergence of two major currents: the ‘social economy’ tradition, originating notably from Europe and Canada; and the ‘solidarity economy’, predominant notably in the Latin American experience, but also increasingly used in other continents. The exchange of experiences and visions from actors across different continents has greatly contributed to this convergence. The main differences and elements in common among scholars and activists are presented in a stylized fashion in entry 3, ‘Contemporary Understandings’, whereby social economy places the emphasis on SSEOEs as part of a ‘third sector’ complementing the capitalist economy and the public sector, while solidarity economy aims at more systemic change, social transformation and political engagement at multiple levels of governance.",
  "The Intercontinental Network for the Promotion of Social Solidarity Economy (RIPESS) is one international SSE coalition that has been instrumental in forging a common identity among strands of social versus solidarity economy. The first in a series of international meetings on the Globalization of Solidarity was held in Lima in 1997, where activists from a wide range of social movements, NGOs, researchers and practitioners from around the world gathered to begin developing the elements of a more concrete global SSE movement. This set the stage for the formal establishment in 2002 of RIPESS, as ‘a global network of continental networks committed to the promotion of Social Solidarity Economy’ in Latin America and the Caribbean, North America, Europe, Africa, Asia and Oceania. Each continental network is composed of national and sectorial networks which provide strong territorial and substantive anchoring to promote intercontinental cooperation and advocacy at different levels.",
  "In the words of former RIPESS board member Emily Kawano, the ‘Social Solidarity Economy is actually a marriage of the solidarity economy and the more radical end of the social economy’. Namely, this refers to social economy actors who see its value in addressing problems such as poverty, unemployment and social exclusion caused by neoliberal capital ism in the short term, but also understand it as a stepping stone toward a more fundamental transformation of the economic system. ‘It is this end of the social economy spectrum that converges with the concept of the solidarity economy’ (Kawano 2013). This reflects the view of many solidarity economy scholars and activists who argue that the SSE agenda must extend beyond the promotion of SSE principles within an organization or enterprise (limited profit, collective ownership and democratic governance). It should not satisfy itself with solely obtaining legal frameworks that guarantee SSEOEs distinct statutory identity without also engaging in the systemic transformation of the prevailing economic system, starting with the promotion of broader solidarity economy ties in the local community and beyond (Laville et al. 2017).",
  "The intercontinental nature of SSE social movements coordinated by established international organizations, such as RIPESS, is an acceptance of nuances in the meaning of terminologies that forges a common identity within a diversity of historical practices and cultural heritage. In Europe, the social economy is quite strongly rooted and pre-dates the framework of the solidarity economy, which has been gaining more support. The RIPESS Europe network, therefore, works with both social economy and solidarity economy organizations and includes sectoral as well as territorial organizations/networks. Quebec builds on the concept of the social economy and seeks to create a movement for transformation that is very practical and grounded at the local and territorial levels. In the rest of Canada, the emphasis is on the ter ritorial framework of local economic development. RIPESS Latin America and the Caribbean uses the solidarity economy framework. Despite some differences in definition, there is broad agreement about its systemic and transformative agenda and is built around a core of ethical principles. The United States Solidarity Economy Network deliberately chose, from the outset, to work within the solidarity economy framework as an unambiguously transformative move ment. The Asia Solidarity Economy Council (ASEC) takes the social enterprise as a starting point, along with the need to build solidarity economy supply chains. RIPESS networks in Africa work with both the social economy and solidarity economy frameworks (RIPESS 2013). One of the achievements of RIPESS was to bring under the SSE umbrella organizations and enterprises that had been practising social and solidarity economy for decades without knowing it.",
  "The SSE Movement and Other Social Movements",
  "From the mid to late 1990s, SSE movements began to converge as a global movement, around the same time that other social movements were coalescing against neoliberal globalization. The mass protests at the 3rd Ministerial Conference of the World Trade Organization in Seattle in 1999 (the so-called ‘Battle of Seattle’) made this global ‘anti-globalization’ movement visible to the mass media and the general public. In previous years, however, a variety of historical events had already revealed distinctive critiques of neoliberal globalization with global interconnections. The Zapatista uprising in Mexico in 1994 was connected to the resist ance to the North American Free Trade Agreement (NAFTA), the worldwide protests against the corporate-driven Multilateral Agreement on Investment that had been initiated by the Organisation for Economic Co-operation and Development (OECD) in 1995, the mobilization against the International Monetary Fund (IMF) in the wake of the 1997‒98 East Asian financial crises, and the massive demonstration of the Jubilee 2000 debt cancellation campaign at the G8 meeting in Birmingham in 1998. All were indicative of a deepening popular discontent against globalization (James and van Seters 2014).",
  "From an initial position primarily focused on being ‘against’ (‘anti-globalization’), prominent actors within the movement took steps to enable this unprecedented global mobilization to move to a new stage of resistance: over and beyond the demonstrations and mass protests, it seemed possible to offer specific proposals ‘for’ (‘alter-globalization’) to seek concrete responses to the challenges of building ‘another world’, one where the economy would serve people and not the other way around. The World Social Forum (WSF) became the vehicle for this effort, spearheaded by a group of Brazilian organizations affiliated to the SSE movement, including CUT (mentioned in Box 1.2), the Landless Peasants’ Movement (MST) of Brazil, the Brazilian Association of Non-Governmental Organizations (ABONG) and the French Association for the Taxation of Financial Transactions and Aid to Citizens (ATTAC). The organizers received the logistical support of the Governor of the Brazilian state of Rio Grande do Sul and the Mayor of Porto Alegre (elected on the pro-SSE workers’ party ‒ PT ‒ platform) where the Forum would be held. A form of global validation of this initiative took place in June 2000, during an ‘alternative’ summit of social movements opposed to globalization organized in coordination with the United Nations Non-Governmental Liaison Service (UN-NGLS) in parallel with the Copenhagen+5 World Summit on Social Development. On that occasion, an International Committee was set up in support of the organization of the first WSF, which was held in late January 2001 and timed to coincide with the World Economic Forum of corporate leaders held annually in Davos (Whitaker 2005).",
  "From the outset, the SSE movement was active in World Social Forum processes to con tribute to the contents of alternatives to the neoliberal agenda at local, national and global levels. This was within the framework of the Forum’s slogan ‘Another World is Possible’ and the motto ‘Resist and Build’, which then framed the content of the 2nd Globalization of Solidarity meeting in Quebec City in October 2001. There were difficulties in making the SSE visible among the multitude of issues and agendas brought by thousands of organizations and movements which gathered in the series of WSF editions that took place since. Some also saw as a handicap the fact that article 1 of the WSF Charter prohibited WSF spokespersons or resolutions from representing the Forum as a whole. The dilution of coherent substantive messaging contributed, among other shortcomings, to a gradual loss of media interest and the lack of any clear normative demands that governments and international institutions could concretely respond to (Savio 2019).",
  "However, a major breakthrough was an agreement to hold a Thematic World Social Forum in Porto Alegre in preparation for the Peoples’ Summit, which was held in parallel with the 2012 United Nations Summit on Sustainable Development (Rio+20). This occasion brought together diverse social movements from around the world, but this time organized around clearly defined cross-cutting thematic clusters, including the SSE, in which RIPESS played a major role, most notably through the Fórum Brasileiro de Economia Solidária (FBES). Among the normative demands emanating from the dialogue between the People’s Summit spokespersons and United Nations (UN) officials was the need for the United Nations to take up the SSE as an alternative to neoliberal globalization capable of addressing the major sustainable development challenges discussed at the official Summit. These demands were heeded, starting with the International Conference on Potential and Limits of Social and Solidarity Economy, organized by the United Nations Research Institute for Social Development (UNRISD) in collaboration with the International Labour Organization (ILO) and UN-NGLS in May 2013 in Geneva. At that meeting, it was decided to create the United Nations Inter-Agency Task Force on Social and Solidarity Economy (UNTFSSE) which was established in September 2013. Its mission, in collaboration with international SSE networks acting as observers, is to raise the visibility of the SSE within the UN system and beyond, notably by showcasing the SSE as a strategic means of implementation of globally agreed Sustainable Development Goals that originated from the follow-up to the Rio+20 Summit (www.unsse.org).",
  "1.4 LOOKING FORWARD",
  "This entry has demonstrated the considerable achievements of the SSE movement, especially over the last two decades. Looking forward, compared to some other social movements that are able to garner global media attention through mass mobilization (such as the climate justice movement and Black Lives Matter), the SSE movement is less visible, in part because the SSE is a more complex concept to convey and it does not lend itself easily to mass mobilization around a catchy slogan. On the other hand, its strength lies in its rootedness at the local level and the fact that it offers concrete benefits to people that are more tangible and immediate than, say, the possible benefits of a hypothetical global Tobin tax, or systemic reforms of the international financial architecture – however much needed these may also remain.",
  "The future of the SSE movement should also be seen in the light of the advent of new social media. While this communication revolution has provided formidable means for rapid mobilization of social movements, it has led to what James and van Seters (2014) have described as a shift from group-based solidaristic movements and place-making to ‘mediated networked politics’, which has engendered limitations to the depth of individual engagement in a transformative politics. When accompanied by a subjectivity that emphasizes autonomy and freedom over other values such as mutuality and reciprocity, networked politics tends to be reduced to symbolic action. Most contemporary activism, rather than producing a transitional practice that might set up alternative ways of living, tends to be reduced to acts of protest and ‘mediated communication’. Mass mobilizations in the age of new social media, such as the Arab Spring of December 2010 and the Occupy Wall Street movement that followed in September 2011, tend to remain limited to ‘communicative protest politics’ with all its strengths and weaknesses. In response, James and van Seters (2014) propose what they call a ‘grounded globalization approach’, suggesting that:",
  "[A]nother world only becomes possible when globalizing social movements are grounded in the local and address the human condition in its fullness: production, exchange, enquiry and organization as well as communication. Prefiguring the claim that ‘another world is possible’, the slogan of the Porto Alegre World Social Forum, requires that exemplary practices are initiated across the full range of human life. (James and van Seters 2014, xxvi)",
  "Therein lies the inherent strength of the global SSE movement in the years to come.",
  "REFERENCES",
  "Addor, Felipe, and Camilla Rolim Laricchia. 2018. \"Incubadoras Tecnológicas de Economia Solidária.\" Rio de Janeiro: Universidade Federal do Rio de Janeiro (UFRJ). https://base.socioeco.org/docs/incubadoras-tecnologicas_v1_1ed2018_web.pdf",
  "Curtis, Russell L., and Louis A. Zurcher. 1973. \"Stable Resources of Protest Movements: The Multi-Organizational Field.\" Social Forces 52 (1): 53. https://doi.org/10.2307/2576423",
  "CUT (Central Única dos Trabalhadores). 1999. \"Sindicalismo e Economia Solidária – Reflexões Sobre o Projeto da CUT.\" http://docvirt.com/DocReader.net/DocReader.aspx?bib=bibliotms&pagfis=10810",
  "Hataya, Noriko. 2017. \"Des Mouvements Promoteurs d’Économie Solidaire en Colombie et au Japon.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, 163–180. Paris: Desclée De Brouwer.",
  "James, Paul, and Paul van Seters. 2014. \"Global Social Movements and Global Civil Society.\" In *Globalization and Politics. Vol. 2: Global Social Movements and Global Civil Society*, edited by Paul James, Nevzat Soguk, Paul van Seters, and James H. Mittelman, vii–xxx. Los Angeles, CA: SAGE.",
  "Kawano, Emily. 2013. \"Social Solidarity Economy: Toward Convergence across Continental Divides.\" UNRISD. https://www.unrisd.org/thinkpiece-kawano",
  "Laville, Jean-Louis, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, eds. 2017. *Mouvements Sociaux et Économie Solidaire*. Paris: Desclée De Brouwer.",
  "RIPESS (Inter-continental Network for the Promotion of Social Solidarity Economy). 2013. \"RIPESS Working Paper: Differences and Convergences in Social Solidarity Economy Concepts, Definitions and Frameworks.\" RIPESS. https://ccednet-rcdec.ca/sites/ccednet-rcdec.ca/files/ccednet/pdfs/doc2_global_vision_base_document_en.pdf",
  "Savio, Roberto. 2019. \"Farewell to the World Social Forum?\" Great Transition Initiative, October 7. https://greattransition.org/gti-forum/wsf-savio",
  "Singer, Paul, and Valmor Schiochet. 2017. \"Économie Solidaire et Parti des Travailleurs au Brésil.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, 355–363. Paris: Desclée De Brouwer.",
  "Whitaker, Francisco. 2005. \"World Social Forum: Origins and Aims.\" Transnational Institute, June 6. https://www.tni.org/en/article/world-social-forum-origins-and-aims",
  "Zimmer, Magali, and Hyungsik Eum. 2017. \"L’Émergence d’Initiatives Solidaires en France et en Corée du Sud.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Jose Luis Coraggio, and Geoffrey Pleyers, 181–197. Paris: Desclée De Brouwer."
],
      fa: [
  "کنشگری و جنبش‌های اجتماعی",
  "مقدمه",
  "با توجه به تنوع تجربه‌های اقتصاد اجتماعی و همبستگی (Social and Solidarity Economy - SSE) در درون کشورها و قاره‌های مختلف و نیز میان آن‌ها، جای شگفتی نیست که پژوهش‌های علمی درباره اقتصاد اجتماعی و همبستگی و جنبش‌های اجتماعی، آکنده از دیدگاه‌ها و برداشت‌های متفاوت باشد؛ به‌ویژه آنکه این دو حوزه معمولاً با رشته‌های متمایز پژوهشی در دانشگاه‌ها پیوند دارند که تاکنون به‌ندرت با یکدیگر تلاقی یافته‌اند.",
  "آیا باید از وجود رابطه‌ای میان اقتصاد اجتماعی و همبستگی و جنبش‌های اجتماعی سخن گفت، یا از نبود چنین رابطه‌ای؟ یا اینکه خودِ اقتصاد اجتماعی و همبستگی را باید جنبشی اجتماعی دانست که بخشی از جنبش‌های گسترده‌تر ــ از سطح محلی تا جهانی ــ است و هدف آن به چالش کشیدن الگوی اقتصادی مسلط نولیبرالی است (Laville et al. 2017)؟",
  "این مدخل بر آن است که هر دو برداشت تا حدی درست هستند. از یک سو، نهادها و زیست‌بوم‌های اقتصاد اجتماعی و همبستگی در بسیاری از نقاط جهان، اغلب حاصل گونه‌های مختلف کنشگری جنبش‌های اجتماعی‌اند؛ خواه پس از شکل‌گیری همچنان با این جنبش‌ها در ارتباط باقی بمانند یا خیر. از سوی دیگر، بخش قابل‌توجهی از منظومه کلی اقتصاد اجتماعی و همبستگی را می‌توان جنبشی اجتماعیِ همگرا ــ یا «جنبشِ جنبش‌ها» ــ توصیف کرد که از مجموعه‌ای متکثر از دیدگاه‌ها تشکیل شده و با دیگر جنبش‌های اجتماعی در تعامل و پیوند است. هدف این جنبش‌ها نه‌تنها مقاومت در برابر پیامدهای زیان‌بار اجتماعی و زیست‌محیطی الگوی اقتصادی کنونی، بلکه نشان دادنِ بدیل‌های عملی و عینی از طریق تجربه و عمل است.",
  "این تجربه‌ها که در سطح سازمان یا بنگاه و نیز در مقیاس قلمروهای محلی شکل می‌گیرند، در صورت فراهم بودن شرایط سیاسی مناسب و وجود انگیزه در میان کنشگران ذی‌ربط، می‌توانند گسترش یابند و از طریق تغییرات توانمندساز در سیاست‌های عمومی، به جریان اصلی تبدیل شوند. در این فرایند، فعالیت‌های دادخواهانه، به چالش کشیدن و اعتراض به سیاست‌ها، تأثیرگذاری بر سیاست‌گذاری، و نیز هم‌ساخت (co-construction) سیاست‌ها از طریق سازمان‌های واسط اقتصاد اجتماعی و همبستگی و متحدان آن‌ها، نقشی اساسی ایفا می‌کند (همچنین بنگرید به مدخل ۵۵، «سازمان‌های پشتیبان و نهادهای واسط» و مدخل ۴۷، «برنامه‌های توسعه محلی و سرزمینی»).",
  "در این مقطع، پرسش اساسی آن است که حاصل نهایی چنین تحولاتی چیست؟ آیا نتیجه آن صرفاً رشد تدریجی فعالیت‌های اقتصادی مبتنی بر اصول اقتصاد اجتماعی و همبستگی در سطوح خرد و میانی است، آن هم در شرایطی که الگوهای ناپایدار تولید و مصرف همچنان تا حد زیادی بدون تغییر باقی می‌مانند؟ یا اینکه این پیشرفت‌ها را باید گام‌هایی برای تحکیم جنبش‌های اجتماعی دانست که در پی ایجاد دگرگونی‌های بنیادین‌تر در سطح کلان، با هدف دموکراتیک‌سازی کل اقتصاد و حتی نظام سیاسی هستند (Laville et al. 2017).",
  "۱.۱ تعریف جنبش‌های اجتماعی در بستر اقتصاد اجتماعی و همبستگی",
  "از دهه ۱۹۷۰ به این سو، جنبش‌های اجتماعی به یکی از موضوعات مهم مطالعات میان‌رشته‌ای دانشگاهی تبدیل شده‌اند. هرچند رویکردهای مختلف علمی، عناصر نسبتاً متفاوتی را برای تعریف آنچه «جنبش اجتماعی» نامیده می‌شود مطرح کرده‌اند، اما برای اهداف این مدخل، از تعریفی استفاده می‌شود که جیمز و ون‌سترس (James and van Seters, 2014) در مطالعه خود درباره بسیج جنبش‌های اجتماعی علیه جهانی‌شدن نولیبرالی، یا همان جنبش «دگرجهانی‌سازی» (alter-globalization)، ارائه کرده‌اند:",
  "تعریف یک جنبش اجتماعی مستلزم وجود چند شرط حداقلی برای «گرد هم آمدن» افراد است: (۱) شکل‌گیری نوعی هویت جمعی؛ (۲) توسعه یک جهت‌گیری هنجاری مشترک؛ (۳) اشتراک در دغدغه تغییر وضعیت موجود؛ و (۴) وقوع مقاطعی از کنش عملی که دست‌کم از منظر ذهنی، در طول زمان به یکدیگر مرتبط باشند و همگی در راستای همین دغدغه تغییر انجام شوند. بر این اساس، ما جنبش اجتماعی را شکلی از کنش سیاسیِ جمعی میان افرادی تعریف می‌کنیم که دست‌کم احساس حداقلی از پیوند با دیگران در چارچوب یک هدف مشترک دارند و طی دوره‌ای نسبتاً طولانی گرد هم می‌آیند تا به نام آن هدف، تغییر اجتماعی ایجاد کنند. (James and van Seters 2014, xi)",
  "افزون بر این عناصر کلی، یکی از ویژگی‌های متمایز جنبش‌های اجتماعیِ مرتبط با اقتصاد اجتماعی و همبستگی ــ به‌ویژه در مقایسه با جنبش‌هایی که عمدتاً بر اعتراض و مخالفت سیاسی استوارند ــ آن است که این جنبش‌ها کنشگری سیاسی را با اشکال مبتنی بر همبستگیِ فعالیت‌های اقتصادی درهم می‌آمیزند. این فعالیت‌ها نه‌تنها می‌توانند شرایط مادی زندگی روزمره مردم را بهبود بخشند، بلکه به‌طور عینی نیز نشان می‌دهند که الگوهای جایگزین اقتصادی، به‌ویژه در سطوح محلی و سرزمینی، امکان‌پذیر هستند (Laville et al. 2017; Zimmer and Eum 2017).در بخش ۱.۴ استدلال خواهد شد که بخش بزرگی از مجموعه گسترده نهادها و سازمان‌هایی که در سراسر جهان خود را بخشی از اقتصاد اجتماعی و همبستگی می‌دانند، از سطح محلی تا سطح جهانی، در عمل به سوی شکل‌گیری یک جنبش اجتماعی ــ یا به تعبیر دیگر، «جنبشِ جنبش‌ها» ــ در حال همگرایی هستند؛ جنبشی که شرایط حداقلی تعریف‌شده برای یک جنبش اجتماعی را برآورده می‌کند، هرچند همانند هر جنبش دیگری، با تنش‌ها و تناقض‌های درونی، و نیز نقاط قوت و ضعف خود در تعامل و همکاری با سایر جنبش‌های اجتماعی روبه‌رو است. با این حال، پیش از پرداختن به این موضوع، این مدخل ابتدا به بررسی نقش جنبش‌های اجتماعی به‌عنوان محرک‌ها و برانگیزانندگان شکل‌گیری اقتصاد اجتماعی و همبستگی می‌پردازد.",
  "۱.۲ جنبش‌های اجتماعی به‌عنوان محرک‌های اقتصاد اجتماعی و همبستگی",
  "ابتکارهای اقتصاد اجتماعی و همبستگی معمولاً حاصل کنشگری جنبش‌های اجتماعی و ائتلاف‌هایی هستند که دارای هم‌سویی‌های مشترک‌اند؛ خواه این هم‌سویی‌ها موضوع‌محور باشند، مانند حفاظت از محیط زیست، کشاورزی بوم‌شناختی، حاکمیت غذایی، سلامت، عدالت اجتماعی و اقتصادی، مقابله با استخراج‌گرایی و منابع مشترک؛ یا هویت‌محور باشند، مانند کشاورزان خرده‌مالک و بی‌زمین، مصرف‌کنندگان، اتحادیه‌های کارگری، انجمن‌های کارگران بخش غیررسمی، جنبش‌های فمینیستی، مردمان بومی و گروه‌های مذهبی. شیوه‌های کنش این جنبش‌ها تا اندازه‌ای توسط بستر سیاسی‌ای که در آن فعالیت می‌کنند تعیین می‌شود. این شیوه‌ها ممکن است اشکال نسبتاً نرم بسیج اجتماعی را دربر گیرند؛ مانند دور زدن نظام تولید و توزیع کشاورزی صنعتی از طریق شبکه‌های محلی و کوتاه تأمین مواد غذایی ارگانیک، یا ایجاد ابتکارهای اقتصاد اجتماعی و همبستگی برای مقابله با بیکاری و ایجاد یا احیای منابع معیشت. گزینه‌ای دیگر، انجام اقدام‌های رادیکال‌تر، مانند اشغال غیرقانونی یا نیمه‌قانونی زمین‌ها و قلمروهاست؛ جایی که «ریزجهان‌های» اقتصاد اجتماعی و همبستگی می‌توانند با درجه‌ای از خودمختاری نسبت به روابط سرمایه‌داری شکل بگیرند. از جمله نمونه‌های این نوع جنبش‌ها می‌توان به جنبش زاپاتیستا در چیاپاسِ مکزیک، جنبش کارگران روستایی بی‌زمین (Movimento dos Trabalhadores Sem Terra, MST) در برزیل، یا جنبش‌های جدیدتر «مناطق قابل دفاع» (Zones à Défendre, ZAD) در فرانسه اشاره کرد (Laville et al. 2017). جنبش‌های اجتماعیِ اقتصاد اجتماعی و همبستگی، همانند دیگر جنبش‌های اجتماعی، زمانی بهتر درک می‌شوند که از رهیافت «میدان چندسازمانی» (multi-organizational field) به آن‌ها نگریسته شود؛ یعنی رویکردی که بر ضرورت فهم این جنبش‌ها در ارتباط با همگرایی جریان‌های فکری گوناگون و جنبش‌های پیشین تأکید دارد (Curtis and Zurcher 1973; Laville et al. 2017). با استفاده از این رویکرد، این مدخل نقش جنبش‌های اجتماعی را در شکل‌گیری و همراهی با شبکه‌های بوم‌کشاورزیِ تولیدکننده ـ مصرف‌کننده در اقتصاد اجتماعی و همبستگی در کره جنوبی و فرانسه (جعبه ۱.۱)، و نیز در ایجاد اشتغال و فرصت‌های معیشتی در کلمبیا و برزیل (جعبه ۱.۲) بررسی می‌کند.",
  "جعبه ۱.۱. جنبش‌های بوم‌کشاورزیِ تولیدکننده ـ مصرف‌کننده در اقتصاد اجتماعی و همبستگی",
  "جمهوری کره",
  "جمهوری کره (کره جنوبی) امروزه یکی از کشورهایی است که پویاترین زیست‌بوم‌های اقتصاد اجتماعی و همبستگی را در جهان دارد و از حمایت بسیاری از دولت‌های محلی برخوردار است؛ همان‌گونه که در مدخل ۴۷، «برنامه‌های توسعه محلی و سرزمینی»، توضیح داده شده است. خاستگاه اقتصاد اجتماعی و همبستگی در این کشور را می‌توان در ایجاد اتحادیه‌های اعتباری توسط جنبش‌های کلیسایی در دهه ۱۹۷۰ جست‌وجو کرد؛ اقدامی که با الهام از جنبش آنتیگونیش (Antigonish Movement) در کانادا صورت گرفت؛ جنبشی که آموزش بزرگسالان، تعاونی‌ها، تأمین مالی خرد و توسعه جوامع روستایی را با یکدیگر تلفیق می‌کرد. از اواسط دهه ۱۹۸۰، با تکیه بر تجربه‌های پیشین تعاونی‌های کشاورزی روستایی، شکل جدیدی از تعاونی‌های مصرف‌کنندگان با نام هانسالیم (Hansalim) پدید آمد که مصرف‌کنندگان و تولیدکنندگان را با هدف ایجاد روابط مبتنی بر همبستگی میان مصرف‌کنندگان شهری و تولیدکنندگان روستایی محصولات ارگانیک گرد هم آورد. ائتلافی از جنبش‌های محیط‌زیستی، فمینیستی، محله‌محور و بسیج شهروندان، به سازمان‌دهی تأمین روزانه محصولات سالم و ارگانیک کمک کرد. مشاهده شده است که این جنبش‌ها در واقع ادامه جنبش‌های پیشین طرفدار دموکراسی در دهه ۱۹۷۰ هستند که علیه دیکتاتوری نظامی شکل گرفته بودند (به‌ویژه دانشجویان، روشنفکران و گروه‌های کلیسایی) و تا امروز نیز فعال مانده‌اند؛ از جمله از طریق تظاهرات گسترده سال‌های ۲۰۱۶ و ۲۰۱۷ که خواستار استیضاح رئیس‌جمهور پارک گئون-هه به دلیل رسوایی فساد بودند. بُعد «جنبش اجتماعی» تعاونی‌های مصرف‌کنندگان نیز همچنان زنده است و این تعاونی‌ها از طریق مشارکت در سازمان‌دهی تظاهرات عمومی در حمایت از حفاظت از محیط زیست و حاکمیت غذایی، این نقش را حفظ کرده‌اند (Zimmer and Eum 2017).",
  "فرانسه",
  "به‌طور مشابه، در فرانسه نیز انجمن‌های حفظ کشاورزی خرده‌مالکی (AMAP) که مشارکت‌های مبتنی بر همبستگی میان کشاورزان خرده‌مالک و مصرف‌کنندگان را ترویج می‌کنند، فعالیت خود را از سال ۲۰۰۱ و در نتیجه تلاش مشترک ائتلافی از جنبش‌های کشاورزان خرده‌مالک، محیط‌زیستی و مصرف‌کنندگان با نام ائتلاف کشاورزان، بوم‌گرایان و مصرف‌کنندگان آغاز کردند؛ ائتلافی که در سال ۱۹۹۱ شکل گرفته بود. از جمله اعضای این ائتلاف، کنفدراسیون کشاورزان، اتحادیه ملی کشاورزان خرده‌مالک و کارگران کشاورزی، است که از یک «بدیل واقع‌بینانه» در برابر کشاورزی صنعتی دفاع می‌کند؛ بدیلی که بر اصول اجتماعی، همبستگی و بوم‌شناختی استوار است. این اتحادیه همچنین یکی از بنیان‌گذاران جنبش جهانی کشاورزان خرده‌مالک، ویا کامپسینا، به‌شمار می‌رود که در سراسر جهان برای ترویج اصول حاکمیت غذایی و همبستگی فعالیت می‌کند (http://confederationpaysanne.fr).",
  "بر اساس آخرین پیمایش‌های انجام‌شده در فرانسه، بیش از ۲۰۰۰ انجمن AMAP وجود دارد و بیش از ۲۵۰ هزار نفر در این جنبش مشارکت دارند؛ چه از طریق شبکه‌های تولیدکننده ـ مصرف‌کننده و چه از طریق فعالیت‌های آگاهی‌بخشی (Zimmer and Eum 2017; http://miramap.org). شبکه ملی این انجمن‌ها، جنبش بین‌منطقه‌ای آماپ، عضو شبکه بین‌المللی اورژنسی است؛ شبکه‌ای از سازمان‌های مردمی که در ۳۲ کشور حضور دارد. این شبکه در کشورهای مختلف، با نام‌های متفاوت، از جمله کشاورزی مورد حمایت جامعه، بر پایه اصول و شیوه‌های عملی مشابهی فعالیت می‌کند و به‌طور کلی با عنوان مشارکت‌های محلی مبتنی بر همبستگی برای کشاورزی بوم‌شناختی شناخته می‌شود. انجمن‌های AMAP بخشی از جنبش گسترده‌تر بوم‌گرایی در فرانسه هستند؛ جنبشی که یک حزب سیاسی با نام سبزها، که اکنون بوم‌گرایان نامیده می‌شود، تشکیل داد. این حزب در حمایت از تدوین و تصویب قانون چارچوب اقتصاد اجتماعی و همبستگی در سال ۲۰۱۴، که از سوی حزب سوسیالیستِ وقتِ حاکم پیشنهاد شده بود، نقش مهمی ایفا کرد (Laville et al. 2017; Zimmer and Eum 2017).",
  "جعبه ۱.۲. جنبش‌های اشتغال و معیشت",
  "کلمبیا",
  "در کلمبیا، ابتکارهای اقتصاد اجتماعی و همبستگی از دهه ۱۹۶۰ پدیدار شدند، هرچند اصول اقتصادی مبتنی بر همبستگی به دوران پیش از اسپانیایی بازمی‌گردد و در قالب شیوه‌های بومیِ کمک متقابل و کنش‌های مبتنی بر بازتولید اجتماعی (با نام‌های مینگا، مانوس وولتاس و کونویتِه) وجود داشته است. از دهه ۱۹۶۰ به بعد، جنبش‌هایی که پروژه‌های عملی اقتصاد اجتماعی و همبستگی را در میدان عمل توسعه می‌دادند، هم‌زمان ایده گنجاندن اصول اقتصاد همبستگی در قانون را نیز ترویج کردند. این جنبش‌ها به‌طور قابل‌توجهی تحت تأثیر کنشگران کاتولیکِ وابسته به الهیات رهایی‌بخش و از طریق دبیرخانه شبانی اجتماعی اسقفی (Sepas) قرار داشتند. همچنین این جریان‌ها از تجربه‌های تعاونی‌گرایی در اروپا و کانادا الهام می‌گرفتند.",
  "فعالان، در شرایطی میان یک رژیم الیگارشیک سرکوب‌گر و گروه‌های چریکی مسلح، اقتصاد اجتماعی و همبستگی را به‌عنوان شیوه‌ای غیرتهدیدآمیز برای بیان ضمنی موضع ایدئولوژیک خود در مخالفت با توسعه سرمایه‌دارانه به کار گرفتند؛ در حالی که هم‌زمان، بدیل‌هایی برای معیشت در برابر گزینه‌های ارائه‌شده توسط نیروهای انقلابی مسلح فراهم می‌کردند.",
  "در منطقه جنوبی ایالت سانتاندر، فعالیت‌ها شامل حمایت از ایجاد و توسعه تعاونی‌ها، عمدتاً در حوزه توسعه روستایی، و همچنین در بخش‌های مالی، حمل‌ونقل، آموزش و سلامت بود. حدود یک‌سوم جمعیت (۴۵۰ هزار نفر) در ۲۰۰ تعاونی ایجادشده فعالیت داشتند. افزون بر این، یک نهاد واسط با نام «ال کومون» ایجاد شد تا امکان گفت‌وگو با دولت را فراهم کند و توسعه سرزمینی اقتصاد اجتماعی و همبستگی را ترویج دهد؛ همچنین شبکه‌هایی میان دانشگاهیان، سازمان‌های غیردولتی و سازمان‌های محلی شکل گرفت تا برنامه‌ریزی و اجرای ابتکارهای توسعه محلی اقتصاد اجتماعی و همبستگی را پیش ببرند.",
  "عناصر مفهوم اقتصاد همبستگی نخستین‌بار در قانون اساسی ۱۹۹۱ وارد شدند. چارچوب حقوقی نهادهای اقتصاد اجتماعی و همبستگی، که در دو دسته «شرکت‌های همبستگی» و «سازمان‌های اقتصادی برای توسعه مبتنی بر همبستگی» طبقه‌بندی شدند، بعدها در قانون ۵۴۵ سال ۱۹۹۸ درباره «اقتصاد همبستگی و نهادهای دارای ماهیت تعاونی» تصریح شد. همچنین قابل توجه است که اقتصاد همبستگی در توافق صلح میان دولت کلمبیا و نیروهای مسلح انقلابی کلمبیا ـ ارتش خلق در سال ۲۰۱۶ نیز به رسمیت شناخته شد (Hataya 2017).",
  "برزیل",
  "در برزیلِ همسایه، جنبش کلیسایی نیز همراه با دیگر جنبش‌های اجتماعی، به‌ویژه جنبش کارگری و امتداد آن در قالب یک حزب سیاسی بزرگ، نقش پیشرو در ایجاد ابتکارهای اقتصاد اجتماعی و همبستگی در سراسر کشور ایفا کرد. سیاست‌های سخت‌گیرانه نولیبرالی در زمینه ریاضت اقتصادی، خصوصی‌سازی و آزادسازی تجاری که در دهه‌های ۱۹۸۰ و ۱۹۹۰ اجرا شد، به بیکاری گسترده و بلندمدت، فقر و طرد اجتماعی در سراسر کشور انجامید. از دهه ۱۹۹۰ به بعد، ابتکارهای اقتصاد اجتماعی و همبستگی در ابتدا به‌عنوان راهبردی برای بقا در میان شمار رو‌به‌افزایش کارگران بیکار شکل گرفتند؛ این ابتکارها در قالب پروژه‌های اجتماعی جایگزین (PACs) توسعه یافتند. این پروژه‌ها توسط نهاد غیردولتی کاتولیک کاریتاس و مراکز رشد اقتصاد اجتماعی و همبستگی با نام «انکوباتورهای فناوری تعاونی‌های مردمی» (ITCP) ایجاد شدند که در دانشگاه‌های عمومی و سازمان‌های غیردولتی مستقر بودند و نتیجه بسیج استادان دانشگاه، دانشجویان، کارگران و کنشگران مردمی بودند. ابتکارهای اقتصاد اجتماعی و همبستگی به‌تدریج با مشارکت طیف گسترده‌تری از جنبش‌ها و گروه‌ها گسترش یافتند، از جمله کارگران روستایی بی‌زمین، جمع‌آورندگان زباله، صنعتگران، مردمان بومی و گروه‌های آفروبرزیلی، جنبش‌های زنان و مجامع محلی.",
  "یکی از دو کنفدراسیون اصلی اتحادیه‌های کارگری ملی، یعنی مرکز متحد کارگران (CUT)، اقتصاد همبستگی را به‌عنوان پاسخی خلاقانه به بحران‌های شدید اقتصادی و آثار ویرانگر آن بر بازار کار پذیرفت. این نهاد در سال ۱۹۹۹ همراه با سایر سازمان‌های غیردولتی و نهادهای اقتصاد اجتماعی و همبستگی، «آژانس توسعه همبستگی» را ایجاد کرد تا از شکل‌گیری و تثبیت تعاونی‌ها و بنگاه‌های همبستگی به‌عنوان ابزار ایجاد اشتغال و درآمد حمایت کند. به‌طور موازی، اقتصاد همبستگی به‌طور فزاینده‌ای در سطح شهرداری‌ها و ایالت‌ها توسط مسئولان منتخب وابسته به حزب سیاسی برخاسته از جنبش کارگری، یعنی حزب کارگران (PT)، حمایت می‌شد. پس از رسیدن این حزب به قدرت در سطح فدرال در سال ۲۰۰۲، دولت آن بین سال‌های ۲۰۰۳ تا ۲۰۱۶ مجموعه گسترده‌ای از سیاست‌ها و برنامه‌های عمومی برای حمایت از اقتصاد اجتماعی و همبستگی توسعه داد؛ از طریق دبیرخانه ملی تازه‌تأسیس اقتصاد همبستگی (SENAES)، همان‌گونه که در مدخل ۴۷، «برنامه‌های توسعه محلی و سرزمینی»، توضیح داده شده است. پس از ایجاد این دبیرخانه، یک نشست عمومی با حضور نمایندگان کل جنبش اقتصاد اجتماعی و همبستگی در کشور برگزار شد که طی آن دو نهاد ملی اصلی ایجاد شدند: «فوروم برزیلی اقتصاد همبستگی» (FBES) که همه ابتکارهای مبتنی بر اقتصاد همبستگی و سازمان‌های جامعه مدنی حامی آن را گرد هم می‌آورد؛ و شبکه‌ای از مسئولان دولت‌های شهری و ایالتی که در قلمروهای خود به ترویج اقتصاد همبستگی می‌پرداختند. بر اساس برخی برآوردها، بیش از ۳۰ هزار سازمان و بنگاه (SSEOEs) و نهادهای پشتیبان در سراسر کشور ایجاد شدند که حدود ۳ میلیون نفر را درگیر می‌کردند (Singer and Schiochet 2017; Addor and Rolim Laricchia 2018; CUT 1999).",
  "برخی از مهم‌ترین کنشگران پیش‌برنده جنبش اقتصاد اجتماعی و همبستگی در برزیل، همچنین در فرایند شکل‌گیری «مجمع اجتماعی جهانی» که در بخش ۱.۳ مورد بحث قرار گرفته است، نقش مؤثری داشتند.",
  "بسیاری از ابتکارها حاصل آمیختگی و تبادل متقابل ایده‌ها و شیوه‌ها میان کشورها و قاره‌های مختلف هستند. موفقیت این ابتکارها در بسیاری از موارد، به ایجاد شتاب سیاسی برای تصویب سیاست‌های عمومی در حمایت از اقتصاد اجتماعی و همبستگی منجر شده است؛ به‌ویژه از طریق احزاب سیاسی‌ای که با جنبش‌های اجتماعی پیشرو هم‌سویی دارند. در برخی موارد، کنشگران ابتکارهای اقتصاد اجتماعی و همبستگی، پس از تثبیت نسبی، از کنشگری جنبشی فاصله می‌گیرند و بر فعالیت‌های اقتصادی روزمره سازمان یا بنگاه خود تمرکز می‌کنند («نهادینه‌شدن» یا routinization)، که این امر می‌تواند به گسستی نسبی یا کامل از جنبش اجتماعی‌ای که آن‌ها را ایجاد کرده بود منجر شود. در موارد دیگر، پیوند با جنبش اجتماعی همچنان فعال باقی می‌ماند یا حتی به شکل جنبش‌های جدیدی تحول می‌یابد (Zimmer and Eum 2017).",
  "۱.۳ اقتصاد اجتماعی و همبستگی: جنبشی جهانی در حال شکل‌گیری در درون جنبش دگرجهانی‌سازی",
  "گسترش اقتصاد اجتماعی و همبستگی از طریق جنبش‌های اجتماعی، حاصل یک نظریه کامل یا نقشه راه از پیش طراحی‌شده و اعمال‌شده از بالا به پایین نیست. بلکه این فرایند، بازتاب یک روند «از پایین به بالا» است که شامل تجربه‌های بسیار متنوعی می‌شود؛ جایی که کنشگران به چالش‌های زمینه‌ای خود پاسخ می‌دهند. در برخی موارد، این کنشگران عملاً فعالیت‌هایی مبتنی بر اصول اقتصاد اجتماعی و همبستگی انجام می‌دهند، بدون آنکه خود را بخشی از یک هویت جمعی به نام «اقتصاد اجتماعی و همبستگی» بدانند.",
  "همان‌گونه که در جعبه‌های ۱.۱ و ۱.۲ مشاهده شد، برخی جنبش‌ها تجربه تعاونی‌گرایی را از کشورهای دیگر مطالعه کرده و اصول آن را در زمینه‌های بومی خود به کار گرفته‌اند. با این حال، تعاونی‌ها تنها بخشی از مجموعه گسترده‌تر نهادها و بنگاه‌های اقتصاد اجتماعی و همبستگی هستند که در دیگر مدخل‌های این دانشنامه توضیح داده شده‌اند. این بخش دو موضوع را بررسی می‌کند: (۱) شرایط همگرایی بخش‌های مهمی از جامعه اقتصاد اجتماعی و همبستگی به‌عنوان یک جنبش اجتماعی جهانی، مطابق با تعریف جیمز و ون‌سترس (۲۰۱۴) که پیش‌تر ذکر شد؛ و (۲) رابطه و هم‌پیوندی میان جنبش اقتصاد اجتماعی و همبستگی و سایر جنبش‌های اجتماعی که علیه دستورکار نولیبرالی بسیج شده‌اند و به‌طور فزاینده‌ای با عنوان جنبش دگرجهانی‌سازی شناخته می‌شوند.",
  "اقتصاد اجتماعی و همبستگی: جنبشی اجتماعی جهانی در حال شکل‌گیری",
  "شکل‌گیری تدریجی هویت جمعی و جهت‌گیری هنجاری مشترک میان کنشگران اقتصاد اجتماعی و همبستگی در سراسر جهان، فرایندی آهسته از گفت‌وگو و یادگیری متقابل بوده است. برای ساده‌سازی آنچه در واقع یک تنوع بسیار گسترده از اصطلاحات و نام‌گذاری‌ها را دربرمی‌گیرد، می‌توان این فرایند را حاصل همگرایی دو جریان اصلی دانست: سنت «اقتصاد اجتماعی» که عمدتاً در اروپا و کانادا ریشه دارد، و «اقتصاد همبستگی» که به‌ویژه در تجربه آمریکای لاتین غالب است، اما به‌تدریج در سایر قاره‌ها نیز مورد استفاده قرار گرفته است. تبادل تجربه‌ها و دیدگاه‌ها میان کنشگران در قاره‌های مختلف نقش مهمی در این همگرایی داشته است. تفاوت‌ها و عناصر مشترک میان پژوهشگران و کنشگران، به‌صورت خلاصه در مدخل ۳، «درک‌های معاصر»، ارائه شده است؛ جایی که اقتصاد اجتماعی بر نهادها و بنگاه‌های اقتصاد اجتماعی و همبستگی به‌عنوان بخشی از «بخش سوم» در کنار اقتصاد سرمایه‌داری و بخش عمومی تأکید می‌کند، در حالی که اقتصاد همبستگی بر تغییرات ساختاری‌تر، تحول اجتماعی و کنش سیاسی در سطوح مختلف حکمرانی تمرکز دارد.",
  "شبکه بین‌قاره‌ای ترویج اقتصاد اجتماعی و همبستگی (RIPESS) یکی از ائتلاف‌های بین‌المللی در این حوزه است که نقش مهمی در شکل‌دهی به یک هویت مشترک میان جریان‌های اقتصاد اجتماعی و اقتصاد همبستگی ایفا کرده است. نخستین مجموعه نشست‌های بین‌المللی درباره «جهانی‌سازی همبستگی» در سال ۱۹۹۷ در لیما برگزار شد؛ جایی که کنشگران طیف گسترده‌ای از جنبش‌های اجتماعی، سازمان‌های غیردولتی، پژوهشگران و فعالان از سراسر جهان گرد هم آمدند تا عناصر یک جنبش جهانی اقتصاد اجتماعی و همبستگی را به‌طور مشخص‌تر توسعه دهند. این روند زمینه را برای تأسیس رسمی RIPESS در سال ۲۰۰۲ فراهم کرد؛ نهادی که به‌عنوان «شبکه‌ای جهانی از شبکه‌های قاره‌ای متعهد به ترویج اقتصاد اجتماعی و همبستگی» در آمریکای لاتین و کارائیب، آمریکای شمالی، اروپا، آفریقا، آسیا و اقیانوسیه شکل گرفت. هر شبکه قاره‌ای از شبکه‌های ملی و بخشی تشکیل شده است که پیوندی محکم با قلمروها و حوزه‌های عملی ایجاد می‌کنند و همکاری و کنشگری بین‌قاره‌ای را در سطوح مختلف تقویت می‌نمایند.",
  "به گفته امیلی کاوانو، عضو پیشین هیئت‌مدیره RIPESS، «اقتصاد اجتماعی و همبستگی در واقع پیوندی است میان اقتصاد همبستگی و رادیکال‌ترین بخش اقتصاد اجتماعی». یعنی آن بخش از کنشگران اقتصاد اجتماعی که ارزش آن را در حل مسائلی مانند فقر، بیکاری و طرد اجتماعی ناشی از سرمایه‌داری نولیبرال در کوتاه‌مدت می‌بینند، اما در عین حال آن را به‌عنوان گامی به سوی تحول بنیادی‌تر نظام اقتصادی نیز درک می‌کنند. «این همان بخشی از طیف اقتصاد اجتماعی است که با مفهوم اقتصاد همبستگی همگرا می‌شود» (Kawano 2013). این دیدگاه بازتاب نظر بسیاری از پژوهشگران و کنشگران اقتصاد همبستگی است که استدلال می‌کنند دستورکار اقتصاد اجتماعی و همبستگی نباید صرفاً به ترویج اصول آن در درون یک سازمان یا بنگاه (مانند سود محدود، مالکیت جمعی و حکمرانی دموکراتیک) محدود بماند. همچنین نباید تنها به ایجاد چارچوب‌های حقوقی‌ای بسنده کند که هویت حقوقی متمایز برای نهادهای اقتصاد اجتماعی و همبستگی فراهم می‌کنند، بدون آنکه در تحول ساختاری نظام اقتصادی مسلط مشارکت داشته باشد؛ تحولی که با گسترش پیوندهای همبستگی در جامعه محلی و فراتر از آن آغاز می‌شود (Laville et al. 2017).",
  "ماهیت بین‌قاره‌ای جنبش‌های اجتماعی اقتصاد اجتماعی و همبستگی که توسط سازمان‌های بین‌المللی تثبیت‌شده‌ای مانند RIPESS هماهنگ می‌شوند، نشان‌دهنده پذیرش تفاوت‌های معنایی در اصطلاحات است که در عین تنوع در تجربه‌های تاریخی و میراث‌های فرهنگی، به شکل‌گیری یک هویت مشترک منجر می‌شود. در اروپا، اقتصاد اجتماعی ریشه‌ای بسیار قوی دارد و پیش از چارچوب اقتصاد همبستگی شکل گرفته است؛ چارچوبی که در سال‌های اخیر حمایت بیشتری به دست آورده است. از این رو، شبکه اروپایی RIPESS با هر دو جریان اقتصاد اجتماعی و اقتصاد همبستگی همکاری می‌کند و شامل شبکه‌ها و سازمان‌های بخشی و همچنین سرزمینی است. در کبک، بر مفهوم اقتصاد اجتماعی تکیه می‌شود و تلاش برای ایجاد یک جنبش تحول‌گرا به‌صورت کاملاً عملی و مبتنی بر سطوح محلی و سرزمینی دنبال می‌شود. در سایر مناطق کانادا، تأکید بر چارچوب سرزمینی توسعه اقتصادی محلی است. شبکه RIPESS آمریکای لاتین و کارائیب از چارچوب اقتصاد همبستگی استفاده می‌کند. با وجود برخی تفاوت‌ها در تعریف، اجماع گسترده‌ای درباره دستورکار نظام‌مند و تحول‌گرای آن و همچنین اصول اخلاقی بنیادین آن وجود دارد. شورای اقتصاد همبستگی آسیا (ASEC) نیز با آغاز از مفهوم بنگاه‌های اجتماعی، بر ضرورت ایجاد زنجیره‌های تأمین اقتصاد همبستگی تأکید دارد. شبکه‌های RIPESS در آفریقا نیز با هر دو چارچوب اقتصاد اجتماعی و اقتصاد همبستگی کار می‌کنند (RIPESS 2013). یکی از دستاوردهای RIPESS این بود که سازمان‌ها و بنگاه‌هایی را که دهه‌ها اقتصاد اجتماعی و همبستگی را در عمل اجرا می‌کردند اما خود را با این عنوان نمی‌شناختند، زیر چتر اقتصاد اجتماعی و همبستگی گرد هم آورد.",
  "جنبش اقتصاد اجتماعی و همبستگی و سایر جنبش‌های اجتماعی",
  "از اواسط تا اواخر دهه ۱۹۹۰، جنبش‌های اقتصاد اجتماعی و همبستگی به‌تدریج به‌عنوان یک جنبش جهانی در حال همگرایی بودند؛ هم‌زمان با آن‌که دیگر جنبش‌های اجتماعی نیز در برابر جهانی‌سازی نولیبرالی در حال شکل‌گیری و انسجام بودند. اعتراضات گسترده در سومین نشست وزرای سازمان تجارت جهانی در سیاتل در سال ۱۹۹۹ (معروف به «نبرد سیاتل») این جنبش جهانی «ضد جهانی‌سازی» را برای رسانه‌های جمعی و افکار عمومی آشکار کرد. با این حال، در سال‌های پیش از آن نیز مجموعه‌ای از رویدادهای تاریخی، نقدهای مشخصی نسبت به جهانی‌سازی نولیبرالی را با پیوندهای جهانی نشان داده بودند. قیام زاپاتیستا در مکزیک در سال ۱۹۹۴ با مقاومت در برابر توافق‌نامه تجارت آزاد آمریکای شمالی (NAFTA) مرتبط بود؛ اعتراضات جهانی علیه توافق چندجانبه سرمایه‌گذاری که توسط سازمان همکاری و توسعه اقتصادی (OECD) در سال ۱۹۹۵ آغاز شده بود؛ بسیج علیه صندوق بین‌المللی پول (IMF) در پی بحران‌های مالی شرق آسیا در سال‌های ۱۹۹۷ و ۱۹۹۸؛ و تظاهرات گسترده کمپین «بدهی ۲۰۰۰» برای بخشش بدهی‌ها در نشست گروه هشت در بیرمنگام در سال ۱۹۹۸. همه این موارد نشان‌دهنده تشدید نارضایتی عمومی نسبت به جهانی‌سازی بودند (James and van Seters 2014).",
  "از یک موضع اولیه که عمدتاً بر «مخالفت» («ضد جهانی‌سازی») تمرکز داشت، کنشگران برجسته این جنبش گام‌هایی برداشتند تا این بسیج جهانی بی‌سابقه را به مرحله‌ای جدید از مقاومت وارد کنند: فراتر از تظاهرات و اعتراضات گسترده، این امکان مطرح شد که پیشنهادهای مشخصی برای «بدیل» («دگرجهانی‌سازی») ارائه شود تا پاسخ‌های عملی برای ساختن «جهانی دیگر» شکل گیرد؛ جهانی که در آن اقتصاد در خدمت مردم باشد، نه برعکس. مجمع اجتماعی جهانی (WSF) به ابزار این تلاش تبدیل شد؛ مجمعی که توسط گروهی از سازمان‌های برزیلی مرتبط با جنبش اقتصاد اجتماعی و همبستگی راه‌اندازی شد، از جمله اتحادیه کارگران (CUT) (ذکرشده در جعبه ۱.۲)، جنبش کارگران بی‌زمین برزیل (MST)، انجمن برزیلی سازمان‌های غیردولتی (ABONG) و انجمن اروپایی مالیات بر تراکنش‌های مالی و حمایت از شهروندان (ATTAC). برگزارکنندگان از حمایت لجستیکی فرماندار ایالت ریو گرانده دو سول و شهردار پورتو آلگره برخوردار شدند (که هر دو از جناح حزب کارگران حامی اقتصاد اجتماعی و همبستگی انتخاب شده بودند)، شهری که میزبان این مجمع بود. نوعی تأیید بین‌المللی این ابتکار در ژوئن ۲۰۰۰ و در جریان یک نشست «جایگزین» جنبش‌های اجتماعی مخالف جهانی‌سازی، که با همکاری سرویس رابط سازمان‌های غیردولتی سازمان ملل متحد (UN-NGLS) و هم‌زمان با اجلاس جهانی توسعه اجتماعی «کپنهاگ+۵» برگزار شد، رخ داد. در آن نشست، کمیته‌ای بین‌المللی برای حمایت از برگزاری نخستین مجمع اجتماعی جهانی تشکیل شد؛ مجمعی که در اواخر ژانویه ۲۰۰۱ برگزار شد و هم‌زمان با نشست سالانه مجمع جهانی اقتصاد در داووس بود (Whitaker 2005).",
  "از ابتدا، جنبش اقتصاد اجتماعی و همبستگی در فرایندهای مجمع اجتماعی جهانی فعال بود تا در تدوین محتوای بدیل‌های دستورکار نولیبرالی در سطوح محلی، ملی و جهانی مشارکت کند. این فعالیت در چارچوب شعار مجمع یعنی «جهانی دیگر ممکن است» و شعار «مقاومت و ساختن» انجام می‌شد؛ شعاری که محتوای نشست دوم جهانی‌سازی همبستگی در کبک در اکتبر ۲۰۰۱ را نیز شکل داد. با این حال، در میان انبوه موضوعات و دستورکارهایی که توسط هزاران سازمان و جنبش در دوره‌های مختلف مجمع اجتماعی جهانی مطرح می‌شد، دشواری‌هایی برای دیده‌شدن اقتصاد اجتماعی و همبستگی وجود داشت. برخی همچنین این موضوع را یک ضعف می‌دانستند که ماده ۱ منشور مجمع اجتماعی جهانی، سخنگویان یا قطعنامه‌های رسمی را از نمایندگی کل مجمع منع می‌کرد. این پراکندگی در پیام‌های منسجم، در کنار کاستی‌های دیگر، به کاهش تدریجی توجه رسانه‌ها و نیز نبود مطالبات هنجاری روشن برای پاسخ‌گویی دولت‌ها و نهادهای بین‌المللی منجر شد (Savio 2019).",
  "با این حال، یک پیشرفت مهم، توافق برای برگزاری یک مجمع اجتماعی جهانی موضوعی در پورتو آلگره بود که در چارچوب آماده‌سازی «اجلاس مردمی» شکل گرفت؛ اجلاسی که هم‌زمان با اجلاس سازمان ملل متحد در سال ۲۰۱۲ درباره توسعه پایدار (ریو+۲۰) برگزار شد. این رویداد، جنبش‌های اجتماعی متنوعی را از سراسر جهان گرد هم آورد، اما این بار آن‌ها حول خوشه‌های موضوعی میان‌بخشیِ مشخص سازمان‌دهی شده بودند که اقتصاد اجتماعی و همبستگی نیز یکی از آن‌ها بود و در آن شبکه RIPESS نقشی مهم ایفا کرد، به‌ویژه از طریق فوروم برزیلی اقتصاد همبستگی (FBES). از جمله مطالبات هنجاری که از گفت‌وگو میان سخنگویان اجلاس مردمی و مسئولان سازمان ملل متحد مطرح شد، این بود که سازمان ملل باید اقتصاد اجتماعی و همبستگی را به‌عنوان بدیلی در برابر جهانی‌سازی نولیبرالی بپذیرد؛ بدیلی که توان پاسخ‌گویی به چالش‌های اصلی توسعه پایدار مطرح‌شده در اجلاس رسمی را داشته باشد.",
  "این مطالبات مورد توجه قرار گرفت و نخستین گام در این مسیر، برگزاری کنفرانس بین‌المللی «توانمندی‌ها و محدودیت‌های اقتصاد اجتماعی و همبستگی» بود که توسط مؤسسه پژوهشی سازمان ملل در توسعه اجتماعی (UNRISD) با همکاری سازمان بین‌المللی کار (ILO) و سرویس رابط سازمان‌های غیردولتی سازمان ملل متحد (UN-NGLS) در مه ۲۰۱۳ در ژنو برگزار شد. در این نشست تصمیم گرفته شد کارگروه بین‌سازمانی سازمان ملل در زمینه اقتصاد اجتماعی و همبستگی (UNTFSSE) ایجاد شود که در سپتامبر ۲۰۱۳ تأسیس گردید. مأموریت این کارگروه، با همکاری شبکه‌های بین‌المللی اقتصاد اجتماعی و همبستگی به‌عنوان ناظر، افزایش دیده‌شدن اقتصاد اجتماعی و همبستگی در درون نظام سازمان ملل و فراتر از آن است؛ به‌ویژه از طریق معرفی آن به‌عنوان یک ابزار راهبردی برای اجرای اهداف توسعه پایدار که در پی‌گیری اجلاس ریو+۲۰ شکل گرفتند (www.unsse.org).",
  "۱.۴ نگاهی به آینده",
  "این مدخل دستاوردهای قابل توجه جنبش اقتصاد اجتماعی و همبستگی را، به‌ویژه در دو دهه اخیر، نشان داده است. با نگاه به آینده، در مقایسه با برخی دیگر از جنبش‌های اجتماعی که می‌توانند از طریق بسیج‌های گسترده توجه رسانه‌های جهانی را جلب کنند (مانند جنبش عدالت اقلیمی و «جان سیاهان مهم است»)، جنبش اقتصاد اجتماعی و همبستگی کمتر دیده می‌شود، بخشی به این دلیل که مفهوم آن پیچیده‌تر است و به‌راحتی در قالب یک شعار جذاب برای بسیج عمومی خلاصه نمی‌شود. در مقابل، نقطه قوت آن در ریشه‌داشتن در سطح محلی است و این واقعیت که منافع ملموس و فوری برای مردم ایجاد می‌کند؛ منافعی که از نظر تجربه زیسته، بسیار ملموس‌تر و مستقیم‌تر از مزایای احتمالی سیاست‌هایی مانند مالیات توبین جهانی یا اصلاحات ساختاری در معماری مالی بین‌المللی است، هرچند این اصلاحات نیز همچنان ضروری باقی می‌مانند.",
  "آینده جنبش اقتصاد اجتماعی و همبستگی را باید در پرتو ظهور رسانه‌های اجتماعی جدید نیز دید. در حالی که این انقلاب ارتباطی ابزارهای قدرتمندی برای بسیج سریع جنبش‌های اجتماعی فراهم کرده است، به گفته جیمز و ون‌سترس (۲۰۱۴) به نوعی تغییر از جنبش‌های مبتنی بر همبستگی گروهی و مکان‌محور به «سیاست شبکه‌ایِ واسطه‌مند» منجر شده است؛ تغییری که محدودیت‌هایی برای عمق مشارکت فردی در سیاست تحول‌گرا ایجاد کرده است. هنگامی که این وضعیت با ذهنیتی همراه شود که بر خودمختاری و آزادی بیش از ارزش‌هایی مانند همیاری و دادوستد متقابل تأکید دارد، سیاست شبکه‌ای به‌سوی تقلیل به کنش‌های نمادین میل پیدا می‌کند. بسیاری از کنشگری‌های معاصر، به‌جای ایجاد عمل گذار که بتواند شیوه‌های بدیل زندگی را شکل دهد، به اعتراض و «ارتباطات واسطه‌مند» محدود می‌شوند. بسیج‌های گسترده در عصر رسانه‌های اجتماعی جدید، مانند بهار عربی در دسامبر ۲۰۱۰ و جنبش اشغال وال‌استریت در سپتامبر ۲۰۱۱، عمدتاً در سطح «سیاست اعتراضی ارتباطی» باقی می‌مانند، با تمام قوت‌ها و ضعف‌های آن.",
  "در پاسخ به این وضعیت، جیمز و ون‌سترس (۲۰۱۴) رویکردی را با عنوان «جهانی‌سازی ریشه‌دار» پیشنهاد می‌کنند و بر این نکته تأکید دارند که:",
  "«جهانی دیگر تنها زمانی ممکن می‌شود که جنبش‌های اجتماعی جهانی‌شونده در سطح محلی ریشه داشته باشند و به وضعیت انسانی در تمام ابعاد آن بپردازند: تولید، مبادله، جست‌وجو و سازمان‌دهی، و همچنین ارتباطات. تحقق ادعای “جهانی دیگر ممکن است”، شعار مجمع اجتماعی جهانی پورتو آلگره، مستلزم آن است که شیوه‌های نمونه‌وار در سراسر طیف کامل زندگی انسانی آغاز شوند» (James and van Seters 2014, xxvi).",
  "در همین‌جا، نقطه قوت بنیادین جنبش جهانی اقتصاد اجتماعی و همبستگی در سال‌های آینده نهفته است.",
  "REFERENCES",
  "Addor, Felipe, and Camilla Rolim Laricchia. 2018. \"Incubadoras Tecnológicas de Economia Solidária.\" Rio de Janeiro: Universidade Federal do Rio de Janeiro (UFRJ). https://base.socioeco.org/docs/incubadoras-tecnologicas_v1_1ed2018_web.pdf",
  "Curtis, Russell L., and Louis A. Zurcher. 1973. \"Stable Resources of Protest Movements: The Multi-Organizational Field.\" Social Forces 52 (1): 53. https://doi.org/10.2307/2576423",
  "CUT (Central Única dos Trabalhadores). 1999. \"Sindicalismo e Economia Solidária – Reflexões Sobre o Projeto da CUT.\" http://docvirt.com/DocReader.net/DocReader.aspx?bib=bibliotms&pagfis=10810",
  "Hataya, Noriko. 2017. \"Des Mouvements Promoteurs d’Économie Solidaire en Colombie et au Japon.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, 163–180. Paris: Desclée De Brouwer.",
  "James, Paul, and Paul van Seters. 2014. \"Global Social Movements and Global Civil Society.\" In *Globalization and Politics. Vol. 2: Global Social Movements and Global Civil Society*, edited by Paul James, Nevzat Soguk, Paul van Seters, and James H. Mittelman, vii–xxx. Los Angeles, CA: SAGE.",
  "Kawano, Emily. 2013. \"Social Solidarity Economy: Toward Convergence across Continental Divides.\" UNRISD. https://www.unrisd.org/thinkpiece-kawano",
  "Laville, Jean-Louis, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, eds. 2017. *Mouvements Sociaux et Économie Solidaire*. Paris: Desclée De Brouwer.",
  "RIPESS (Inter-continental Network for the Promotion of Social Solidarity Economy). 2013. \"RIPESS Working Paper: Differences and Convergences in Social Solidarity Economy Concepts, Definitions and Frameworks.\" RIPESS. https://ccednet-rcdec.ca/sites/ccednet-rcdec.ca/files/ccednet/pdfs/doc2_global_vision_base_document_en.pdf",
  "Savio, Roberto. 2019. \"Farewell to the World Social Forum?\" Great Transition Initiative, October 7. https://greattransition.org/gti-forum/wsf-savio",
  "Singer, Paul, and Valmor Schiochet. 2017. \"Économie Solidaire et Parti des Travailleurs au Brésil.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Geoffrey Pleyers, and Jose Luis Coraggio, 355–363. Paris: Desclée De Brouwer.",
  "Whitaker, Francisco. 2005. \"World Social Forum: Origins and Aims.\" Transnational Institute, June 6. https://www.tni.org/en/article/world-social-forum-origins-and-aims",
  "Zimmer, Magali, and Hyungsik Eum. 2017. \"L’Émergence d’Initiatives Solidaires en France et en Corée du Sud.\" In *Mouvements Sociaux et Économie Solidaire*, edited by Jean-Louis Laville, Elisabetta Bucolo, Jose Luis Coraggio, and Geoffrey Pleyers, 181–197. Paris: Desclée De Brouwer."
],
    },
  },
];

export function getArticleBySlug(slug: string) {
  return articles.find((article) => article.slug === slug) ?? null;
}

export function getLocalizedArticle(slug: string, locale: ArticleLocale) {
  const article = getArticleBySlug(slug);

  if (!article) {
    return null;
  }

  return {
    ...article,
    title: article.title[locale],
    description: article.description[locale],
    category: article.category[locale],
    body: article.body[locale],
  };
}
